---
include:
###################
### CORNE START ###
###################

# peripheral_left + nice_nano_v2 + nice_epaper
  - board: nice_nano_v2
    shield: corne_left_peripheral nice_view_adapter nice_epaper
    artifact-name: nice_corne_left_peripheral_view

# peripheral_left + nice_nano_v2 + nice_epaper
  - board: nice_nano_v2
    shield: corne_right_peripheral nice_view_adapter nice_epaper
    artifact-name: nice_corne_right_peripheral_view

# Xiao_Dongle START
  - board: seeeduino_xiao_ble
    shield: corne_dongle_xiao
    #  -DCONFIG_ZMK_USB=y  -DCONFIG_ZMK_BLE=y
    cmake-args: 
      - -DCONFIG_ZMK_KEYBOARD_NAME=\"Xiao_Dongle\"
      - -DCONFIG_ZMK_STUDIO=y
      - -DCONFIG_ZMK_STUDIO_LOCKING=n
      - -DCONFIG_ZMK_IDLE_TIMEOUT=60000
      - -DCONFIG_ZMK_USB=y
      - -DCONFIG_ZMK_BLE=y
    artifact-name: xiao_corne_dongle
    snippet: studio-rpc-usb-uart

#################
### CORNE END ###
#################

####################
### LILY58 START ###
####################

  # peripheral_right
  - board: nice_nano_v2
    shield: lily58_right_peripheral
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_lily58_right_peripheral

  # peripheral_left
  - board: nice_nano_v2
    shield: lily58_left_peripheral
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_lily58_left_peripheral

# Xiao_Dongle_Prospector
  - board: seeeduino_xiao_ble
#    shield: lily58_dongle_xiao prospector_adapter
    shield: lily58_dongle_xiao dongle_screen
    cmake-args: 
      #- -DCONFIG_ZMK_KEYBOARD_NAME=\"lily58Dongle_X\" 
      - -DCONFIG_ZMK_STUDIO=y
      - -DCONFIG_ZMK_STUDIO_LOCKING=n
      - -DCONFIG_ZMK_IDLE_TIMEOUT=60000
      #- -DCONFIG_LV_COLOR_DEPTH=16
      #- -DCONFIG_LV_COLOR_DEPTH_16=y
      #- -DCONFIG_LV_COLOR_DEPTH_1=n
      #- -DCONFIG_LV_COLOR_16_SWAP=n
    artifact-name: xiao_lily58_dongle_xiao
    snippet: studio-rpc-usb-uart

##################
### LILY58 END ###
##################

############################
### AURORA SOFLE START ###
############################

  # peripheral_right
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_right
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000 -DCONFIG_ZMK_RGB_UNDERGLOW=y -DCONFIG_ZMK_DISPLAY=y -DCONFIG_EC11=y -DCONFIG_EC11_TRIGGER_GLOBAL_THREAD=y -DCONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
    artifact-name: nice_sofle_right

  # peripheral_left
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_left_peripheral
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000 -DCONFIG_ZMK_RGB_UNDERGLOW=y -DCONFIG_ZMK_DISPLAY=y -DCONFIG_EC11=y -DCONFIG_EC11_TRIGGER_GLOBAL_THREAD=y -DCONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
    artifact-name: nice_sofle_left_peripheral

  # Xiao_Dongle
  - board: seeeduino_xiao_ble
    shield: splitkb_aurora_sofle_dongle_xiao dongle_screen
    cmake-args:
      - -DCONFIG_ZMK_KEYBOARD_NAME=\"Sofle_Dongle\"
      - -DCONFIG_ZMK_STUDIO=y
      - -DCONFIG_ZMK_STUDIO_LOCKING=n
      - -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: xiao_sofle_dongle
    snippet: studio-rpc-usb-uart

####################
### AURORA SOFLE END ###
####################

############################
### SETTINGS_RESET START ###
############################W

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_settings_reset

##########################
### SETTINGS_RESET END ###
##########################
