manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: prospector
      url-base: https://github.com/t-ogura

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # Display & IO modules
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main

    - name: zmk-dongle-display-view
      remote: mctechnology17
      revision: main

    - name: zmk-oled-adapter
      remote: mctechnology17
      revision: main

    # Keyboard-specific modules
    - name: prospector-zmk-module
      remote: prospector
      revision: v2.2.1
      path: modules/prospector-zmk-module

  self:
    path: config
